### ISSUE TITLE
PDF Compare

### ISSUE THREAD

**Issue by venkivb4u** [groupdocs-comparison/GroupDocs.Comparison-for-.NET#63]
Hello -

I am trying to compare two pdf and find the difference. When I run the below code, the code is always getting stuck at "Compare" function and I do not know what is going on. Please assist. Let me know if you need anything further.

          using (FileStream fileStream = File.OpenRead("---Temporary License Path----"))
            {
                License license = new License();
                license.SetLicense(fileStream);
            }

            string sourceDocumentPath = "----actual path to source document----"; 
            string targetDocumentPath = "-----actual path to target document-----"; 
            string outputPath = "----actual path to result document------------------"; 

            using (Comparer comparer = new Comparer(sourceDocumentPath))
            {
                CompareOptions compareOptions = new CompareOptions
                {
                    HeaderFootersComparison = false,
                    SensitivityOfComparison = 100,
                };

                comparer.Add(targetDocumentPath);
                comparer.Compare(File.Create(outputPath), new SaveOptions(), compareOptions);
            }

**Comment by kegor** [comment]
Hi @venkivb4u,

Sorry for such a long delay.
I tried to reproduce the issue using library version 20.6.0, but the code above finished successfully without getting stuck.

If the issue still actual could you please share your test-files and version of the `GroupDocs.Comparison` library that you use.

Thank you,
Egor.
